sudo: false
language: java
jdk:
- oraclejdk8
addons:
  postgresql: '9.4'
  mysql: 5.6.26
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - secure: p7SoKCVTQgmbKmrMT7PV9zSTmQmvss+DZuw9KvpI65acMvhP1hp1/7fpspminr2+4HYDpcI9NKfZfwDcBXKNGlgG8BI73cIR3datnVopKYdQB7tG477Gl27+9320N9zXqJn63nLiHtLg0SxOU9Kvg4SptG/+HFqMTCJwi/bN7rb+6vPw9gWR72/7IcufkcFM4vqd6TG0TDtWsYPGqaL8pNXIHXgjkch+jDipb+XAp9vh8cbwpRC+zg9hIE7z6MeJRyMG7+Cu9yCPLZIYhclMj8XtcKnaRdl2pO9DWH5EW8ryhSj9MIyGW4NszFh4HqbVtWnY74Dd5ChMFEDrZYhkH8krvJRQXrRaX5QpAWeC1A2MkJGVKLGdOCyprEBf/pRrh2TW2+oK4oSsUtg97kkAgUcsNa6lJMq1it9X7xHTkSBZ5m0p53V0cwxxcM5TiqZJjkzdLMcsCAB8T9prn4Q5mLBs33UwtK6GmN4jgTOThsH6lSNl6oUTeQV2kr1xZJpDzgfZgPuM71AxJEjIza+5tDiVGx/nqk7itFD0Lg+p/0VAhMH9p4YYyBve2vSvs2yI4hfXdSgNTzlfRpAGVKAGHsNktyNcagO0n525d67fUCWWm52kYQQcAJty3fvjaDS7nF1iyHpD5g3OEAFYgQSzG+YVseNOpmhEk4UREcsX+6s=
  - secure: Ue7N2EO0qZ+VcesrjA7EHHgYwLhTVqIZiLmny92061Is3cx1Zz5n/NjU3wW9SG0P5jjXGhyLbcK7ZNh9OAKboGvxxzXChJE3w93lys7MguvQ7MfIWjorGpIzRwBJosqh5ZdRsoHkyjAazjAma0x6qNs4Ms/eBlNfzdjody9+61492e6cQriIWQjwvWLmO9QKIxnYP+N26SHoSx09fw/Xp8Ir/3pNPYpjRCxJmKhiTGMB3ryRjrK7Mhacf2rrVGZ15j1lqlCH95ZNFbBymkTGDHhbjKPyWXq4yEL04XR3ib0oE8nhg/avceka+P7BQkNQ8ARkO6iIRqXIKYsNe5mij/nYlCfg03Jc/Amuv3eYwIEhFok4NvPyVGMnH5YAkwklOrNZK4Tg1i4E/OIv29fX39UJy+UH/wqg1kbA45uCO54A+yLESY24d3imTeCrtk5/TGsWzZJLZ+GjaE6E9IA4FrDdLlMbK+jrBvKdjBPp7LwbSlyhJp2jY4eaDx/q5lw5rEckWgAP1ezIiq+PmDCNcGyKuCtnljagK0L0wBpwzxa9/L0Uob/685yNWFMoXiGkD2QF2MIaYc1RK9GXbFDZPseK4+cTrIvHtPOzR2tizCR1dxpN2VMVcTdowWY76NvTt3dOQ8DAVoQXWgZ6zcFjTF15oN4jJT+cYssWHVDvNqg=
  - secure: D0F4zdZDnmHO6jSOLo4oIOzZUqDyAoB4ko8xHuI+SNwwIxsEDLbKd2P8wWCOhjqIsZPP6X1N5nTr/J1AqueDT7bVdqIA0zIEJe889Xy0Onk2aMT5UuLPqbmkANK7TnBQqHLsU6xEpsC/dOnBG4u/m+FDyYyVpw4/tkKeEHKp2tVqnbInbrISKFWU2WHvsu/SLIcgYPHqvVye/Ywa8UrPGlMx1ROuKPpa9AnCqVeVrV1UkuEjqgPXDF1JuWAlqiYMZmdCQSMA4akLU5boT/Dr90YhdsxzEKWvkT47SHf+HFMDOZU+T9J5ksnIkJexhXpzD2JZM7CIgQjoBSdeV4RCgixtZh+5g80AG1e2MRDEvOEGYWoQ7YQ+gc7A1iwDZk0M/ZDG9iicJkGydBiJPxRc3ba8cW821yziO494/F8BpTaWTwkQdS8DIFmkanIR8sDemMJo4IUwgNrRcYPLDEJtuMsKaD6pajK2p+vsAlARxGefSMQ2khz5BZ8yXeZvb4k1En7QnVPtH2KbYfP6x7RGylx1C3uC5xF0Id4wpa2l8brkJtri5PaP1iWccLc9zcCqKDSVdkMB51FqcVbhtth6vhWNBqiFALIIifQ8/0rLpvUGd78eKBC28fzyCGFoZedxge2ICqY/fQs+zxpoEV7zqKmSav/QBVc0h0Upsu9mqx0=
before_install:
- openssl aes-256-cbc -k "$codemonastery_passphrase" -in .travis/release-settings.xml.enc
  -out .travis/release-settings.xml -d
- openssl aes-256-cbc -k "$codemonastery_passphrase" -in .travis/cm.private.key.enc
  -out .travis/cm.private.key -d
- gpg --import .travis/cm.key
- gpg -v --allow-secret-key-import --import .travis/cm.private.key
install: mvn -DskipTests=true -Dbasepom.check.skip-all=true -B install
script: bash .travis.sh
after_success:
- bash .travis_after_success.sh
notifications:
  slack:
    secure: Ni9WJElUg2OyXkd1JtRYgEDVJ4MG37WrgzHo5XZruNiDjfWBKTkau8lEQuNPSx11bMNyz2iZlf18Xm0zoV+sLBxq2tYzaXhnhMdf6AdOosQ6SrCUjA1TjYKX8PYLaFRNnPlHjbkA9OQVp4O1y7jacWdTFd/3r/GbTRFepcKhxfYuhi1DlCjRqxTEG91nhFVOhbY+hLeLUSHLTUlk7l587hRRSKhE4uOK4DSRD00GQ92UM1ubaECIiyjofT+Z6IidEqdA8abdYFR7DAt+IbpGZwAGffNZOWLi7VLEpvo+94aoyIk6DnCpGXqNG4P/3MNOFUDBqdT0yHpFuQIcLG9hU1kBxv/txI04OxybLpBAWL6fxmpTc/oQDF7er4tlVeXWGUchzbRWv2fI5dS+w4X4JKqX/mnbcf+W2Gql/fVGGRrJrmYU+0cAB+egucgPKX2F+EmKfrnmQO9ss10XzWPhwgWPNnWVrc1T427HD5oqItn4vANIj5PtyjnUT0kaCYem6JDmg3IYLsm56PnJHh/ElzKVHzgokOnT/xu1uJMlRksMYYmt+zesuIFkvJY/kKinnp25XFVnCkDVFtdVf8e4KK6ZKdqcOX3yqjFDgxSJhij6q1sdf1qF/nerOqNGVWpfeka9pqLqjnUVv4YRdDx9A0o0bRg5Wd9H/kZJHKhqfjw=
