language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
sudo: false
addons:
  apt:
    packages:
      - gpg2
install: mvn -DskipTests=true -Dbasepom.check.skip-all=true -B install
script: mvn -B verify
after_success:
  - mvn clean test jacoco:report coveralls:report