language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
addons:
  postgresql: "9.4"
cache:
  directories:
    - $HOME/.m2
sudo: false
install: mvn -DskipTests=true -Dbasepom.check.skip-all=true -B install
script: ./travis_script.sh
